use_frameworks!

platform :ios, '9.0'

target 'HWJavaScriptBridge_Example' do
  pod 'HWJavaScriptBridge', :path => '../'

  target 'HWJavaScriptBridge_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
